
import { calcSkillFactor } from "./SkillsService.js";
import { calcSkillFactorR } from "./SkillsServiceR.js";

console.log("Participant Aikon(272) in Accuracy(2) all time: ")
console.log(calcSkillFactor(272, 3))
console.log("Participant Aikon(272) in Accuracy(2) seasonYear(2): ")
console.log(calcSkillFactor(272, 3, 2))
console.log("---------------")
console.log("---------------")
console.log("R - Participant Aikon(272) in Accuracy(2) all time: ")
console.log(calcSkillFactorR(272, 3))
console.log("R - Participant Aikon(272) in Accuracy(2) seasonYear(2): ")
console.log(calcSkillFactorR(272, 3, 2))
console.log("R - Participant Aikon(272) in Accuracy(2) seasonYear(5): ")
console.log(calcSkillFactorR(272, 3, 5))
console.log("---------------")
console.log("---------------")
console.log("R - Participant ØreByte(154) in Creativity(5) all time: ")
console.log(calcSkillFactorR(154, 5))
console.log("R - Participant ØreByte(154) in Creativity(5) seasonYear(2): ")
console.log(calcSkillFactorR(154, 5, 2))
console.log("R - Participant ØreByte(154) in Creativity(5) seasonYear(5): ")
console.log(calcSkillFactorR(154, 5, 5))
console.log("---------------")
console.log("R - Participant ØreByte(154) in Speed(1) all time:")
console.log(calcSkillFactorR(154, 1))
console.log("R - Participant ØreByte(154) in Speed(1) seasonYear(5): ")
console.log(calcSkillFactorR(154, 1, 5))
console.log("R - Participant ØreByte(154) in Speed(1) seasonYear(2): ")
console.log(calcSkillFactorR(154, 1, 2))
console.log("R - Participant ØreByte(154) in Speed(1) seasonYear(7): ")
console.log(calcSkillFactorR(154, 1, 7))
console.log("---------------")
console.log("---------------")